services:
  db:
    restart: "no"
    ports:
      - "127.0.0.1:5433:5432"

  adminer:
    restart: "no"
    ports:
      - "8081:8080"

  backend:
    restart: "no"
    ports:
      - "8001:8000"
    build:
      context: .
    # command: sleep infinity  # Infinite loop to keep container alive doing nothing
    command:
      - fastapi
      - run
      # - --reload
      - "app/main.py"
    develop:
      watch:
        - path: .
          action: sync
          target: /app
          ignore:
            - ./.venv
            - .venv
        - path: ./pyproject.toml
          action: rebuild
    # TODO: remove once coverage is done locally
    # volumes:
    #   - ./htmlcov:/app/htmlcov
    # Removed mailcatcher SMTP configuration - now using Google SMTP
    # environment:
    #   SMTP_HOST: "mailcatcher"
    #   SMTP_PORT: "1025"
    #   SMTP_TLS: "false"
    #   EMAILS_FROM_EMAIL: "noreply@example.com"

# Removed mailcatcher service - now using Google SMTP
# mailcatcher:
#   image: schickling/mailcatcher
#   ports:
#     - "1080:1080"
#     - "1025:1025"

# networks:
#   traefik-public:
#     # For local dev, don't expect an external Traefik network
#     external: false
